# -*- coding: utf-8 -*-
"""Hackatón.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GG_JwR70ubNZ-Hp-y6eRHyFzwEV2NV0
"""

st.title('Uber pickups in NYC')

st.write("""
#hackatón
odio todo
""")